name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install --no-audit --no-fund

            - name: Build
              run: npm run build

            - name: Ensure .nojekyll (so GitHub Pages serves _next/)
              run: |
                mkdir -p out
                touch out/.nojekyll

            - name: Fix asset paths for GitHub Pages
              # Replace repo-prefixed asset paths like /<repo>/_next/... with relative ./_next/... so Pages resolves them reliably
              run: |
                if [ -f out/index.html ]; then
                  sed -i"" -e 's/\/dilware-myself-frontend-web-fecha-hora-clima\/_next/.\/_next/g' out/index.html || true
                fi
                if [ -f out/404.html ]; then
                  sed -i"" -e 's/\/dilware-myself-frontend-web-fecha-hora-clima\/_next/.\/_next/g' out/404.html || true
                fi

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out
                  publish_branch: gh-pages
