name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies (clean)
              run: npm ci --no-audit --no-fund

            - name: Build (increase node memory)
              env:
                  NODE_OPTIONS: --max_old_space_size=4096
              run: npm run build

            - name: Ensure .nojekyll (so GitHub Pages serves _next/)
              run: |
                  mkdir -p out
                  touch out/.nojekyll

            - name: Fix asset paths for GitHub Pages
              # Replace repo-prefixed asset paths like /<repo>/_next/... with relative ./_next/... so Pages resolves them reliably
              run: |
                  REPO_PREFIX="/dilware-myself-frontend-web-fecha-hora-clima/_next"
                  REPLACE="./_next"
                  if [ -f out/index.html ]; then
                    # Try POSIX sed first
                    sed -i -e "s|${REPO_PREFIX}|${REPLACE}|g" out/index.html || true
                    # If sed failed (rare), fallback to perl in-place
                    perl -0777 -pe "s|${REPO_PREFIX}|${REPLACE}|g" -i out/index.html || true
                  fi
                  if [ -f out/404.html ]; then
                    sed -i -e "s|${REPO_PREFIX}|${REPLACE}|g" out/404.html || true
                    perl -0777 -pe "s|${REPO_PREFIX}|${REPLACE}|g" -i out/404.html || true
                  fi

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out
                  publish_branch: gh-pages
